# Generated by Django 2.2.7 on 2019-11-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='token',
        ),
        migrations.AddField(
            model_name='notification',
            name='module_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
